#!/usr/bin/env bash

#SBATCH --partition=pibu_el8                                                                                                          
#SBATCH --error=log/maker_%j.err                                                                                                        
#SBATCH --out=log/maker_%j.out                                                                                                          
#SBATCH --mem=10G                                                                                                                        
#SBATCH --job-name=edta                                                                                                              
#SBATCH --time=00:30:00                                                                                                                 
#SBATCH --mail-user=hector.arribasarias@students.unibe.ch                                             
#SBATCH --mail-type=end                                       
#SBATCH --cpus-per-task=4

# this script creates the control file for maker

# generate and go to working directory
WORKDIR=/data/users/harribas/assembly_course/annotation/output/gene_annotation
mkdir -p $WORKDIR
cd $WORKDIR

# generate the control files required for MAKER
apptainer exec --bind $WORKDIR \
/data/courses/assembly-annotation-course/CDS_annotation/containers/MAKER_3.01.03.sif maker -CTL
