#!/bin/bash
#SBATCH --time=4-0
#SBATCH --mem=64G
#SBATCH -p pibu_el8
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=50
#SBATCH --job-name=Maker
#SBATCH --output=log/Maker_format%j.out
#SBATCH --error=log/Maker_format%j.err

COURSEDIR="/data/courses/assembly-annotation-course/CDS_annotation"
WORKDIR="/data/users/harribas/assembly_course/annotation/output/gene_annotation"
REPEATMASKER_DIR="/data/courses/assembly-annotation-course/CDS_annotation/softwares/RepeatMasker"
CONTROL_FILES="/data/users/harribas/assembly_course/annotation/output/gene_annotation"

export PATH=$PATH:"/data/courses/assembly-annotation-course/CDS_annotation/softwares/RepeatMasker"

# go to directory where configuration files are
cd $WORKDIR

# load modules
module load OpenMPI/4.1.1-GCC-10.3.0
module load AUGUSTUS/3.4.0-foss-2021a

# run container with maker
mpiexec --oversubscribe -n 50 apptainer exec \
--bind $SCRATCH:/TMP --bind $COURSEDIR --bind $AUGUSTUS_CONFIG_PATH --bind $REPEATMASKER_DIR --bind $WORKDIR \
${COURSEDIR}/containers/MAKER_3.01.03.sif \
maker -mpi --ignore_nfs_tmp -TMP /TMP \
${CONTROL_FILES}/maker_opts.ctl \
${CONTROL_FILES}/maker_bopts.ctl \
${CONTROL_FILES}/maker_evm.ctl \
${CONTROL_FILES}/maker_exe.ctl 
